### ISSUE TITLE
Works?

### ISSUE THREAD

**Issue by Mawfyy** [TheBearodactyl/geode-sdk-rs#1]
I'd like to join this but i don't know about if this project would work or there's some disadvantages

**Comment by TheBearodactyl** [comment]
> I'd like to join this but i don't know about if this project would work or there's some disadvantages

@Mawfyy 
It'd be great if you could join :D
It could work, here's a similar project: https://github.com/zeozeozeo/geometrydash
And the whole point is that Geode being written in C++ has EXTREME disadvantages opposed to Rust!

**Comment by TheBearodactyl** [comment]
new repo is here btw: https://github.com/TheBearodactyl/geode/tree/rwiir

**Comment by Mawfyy** [comment]
> new repo is here btw: https://github.com/TheBearodactyl/geode/tree/rwiir

Thanks, you have discord server or something?

**Comment by TheBearodactyl** [comment]
> > new repo is here btw: https://github.com/TheBearodactyl/geode/tree/rwiir
> 
> Thanks, you have discord server or something? 

@Mawfyy \@thebearodactyl (if you mean a server, i can make one)

not gonna be available after 10 tonight btw, sorry D:

edit: lemme make a server

**Comment by TheBearodactyl** [comment]
> > new repo is here btw: https://github.com/TheBearodactyl/geode/tree/rwiir
> 
> Thanks, you have discord server or something? 

@Mawfyy sent you an invite on discord!
